name: CD - Deploy to Local Machine (Windows + Private Docker Hub)

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Login to Docker Hub AND expose credentials to shell
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false

      - name: Manual Docker login + Deploy (Windows 100% working)
        shell: powershell
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          Write-Output "IT'S ALIVE!!!"; docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_TOKEN; docker pull pauanesh-kumar/sampleappdockerimagecicdlinuxv1:latest; docker rm -f sampleapp; docker run -d --name sampleapp -p 8080:80 --restart unless-stopped pauanesh-kumar/sampleappdockerimagecicdlinuxv1:latest; Write-Output "OPEN NOW: http://localhost:8080"
