name: CD - Deploy to Local Machine

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy container
        shell: powershell
        run: |
          Write-Output "Pulling image..."
          docker pull pauanesh-kumar/sampleappdockerimagecicdlinuxv1:latest

          Write-Output "Removing old container..."
          docker rm -f sampleapp || $true

          Write-Output "Starting new container..."
          docker run -d --name sampleapp -p 8080:80 --restart unless-stopped `
            pauanesh-kumar/sampleappdockerimagecicdlinuxv1:latest

          Write-Output "IT'S ALIVE!"
          Write-Output "http://localhost:8080"
